import js from '@eslint/js';
import prettier from 'eslint-config-prettier';

export default [
  js.configs.recommended,
  prettier,
  {
    files: ['**/*.js'],
    ignores: ['dist/**', 'node_modules/**', '.husky/**'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        clearTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        AudioContext: 'readonly',
        SpeechRecognition: 'readonly',
        webkitSpeechRecognition: 'readonly',
        speechSynthesis: 'readonly',
        SpeechSynthesisUtterance: 'readonly',
        MutationObserver: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        crypto: 'readonly',
        Blob: 'readonly',
        FormData: 'readonly',
        FileReader: 'readonly',
        URL: 'readonly',
        Image: 'readonly',
        globalThis: 'readonly',
        firebase: 'readonly',
        indexedDB: 'readonly',
        MediaRecorder: 'readonly',
        AbortController: 'readonly',
        atob: 'readonly',
        btoa: 'readonly',
        prompt: 'readonly',
        __initial_auth_token: 'readonly',
        __server_base: 'readonly',
        escapeHtml: 'readonly',
        selectQuizOption: 'readonly',
        submitQuizAnswer: 'readonly',
        startQuiz: 'readonly',
        perkinsKeysPressed: 'writable',
        currentAgeLevel: 'readonly',
        __app_id: 'readonly',
        __firebase_config: 'readonly',
        self: 'readonly',
        caches: 'readonly',
        runInit: 'readonly',
        Response: 'readonly',
      },
    },
    rules: {
      'no-var': 'error',
      'prefer-const': 'error',
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrors: 'none' }],
      'no-console': 'off',
      semi: ['error', 'always'],
      quotes: ['error', 'single', { avoidEscape: true }],
      eqeqeq: ['error', 'always'],
      curly: 'error',
      'no-throw-literal': 'error',
      'prefer-template': 'warn',
      'no-empty': ['warn', { allowEmptyCatch: true }],
    },
  },
  {
    files: ['worker/**/*.js'],
    languageOptions: {
      globals: {
        window: 'off',
        document: 'off',
        navigator: 'off',
        localStorage: 'off',
        AudioContext: 'off',
        SpeechRecognition: 'off',
        speechSynthesis: 'off',
        MutationObserver: 'off',
        requestAnimationFrame: 'off',
        caches: 'off',
        env: 'readonly',
        addEventListener: 'readonly',
        Response: 'readonly',
        Request: 'readonly',
        TextEncoder: 'readonly',
        TextDecoder: 'readonly',
        crypto: 'readonly',
        atob: 'readonly',
      },
    },
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      globals: {
        describe: 'readonly',
        it: 'readonly',
        test: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        jest: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'off',
    },
  },
];
