name = "cloud-school-api"
main = "worker/index.js"
compatibility_date = "2025-04-16"

[[kv_namespaces]]
binding = "DATA"
id = "e7dab1f829384c019ad6079674f58013"

[[kv_namespaces]]
binding = "SESSIONS"
id = "59791fab3a5f4a1e888160154d53eba3"

[[kv_namespaces]]
binding = "CONFIG"
id = "d2ded6e401a6472ea2e0d03a24dba9fc"

[vars]
CORS_ORIGIN = "https://cloud-school-6251a.web.app"
FIREBASE_API_KEY = "AIzaSyCB-560lR7KyRyD9TYShxdJbkoP8rELBuw"
